name: Creation of Azure_VM
on:
  workflow_dispatch:
jobs:
  review:
    runs-on: self-hosted
    environment: review
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: azure view deployment changes
        run: |
              cd apim-tf
              terraform init
              terraform plan
   
  DEV:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: create azure_vm in DEV ENV
        run: |
              cd apim-tf
              terraform init
              terraform apply
    


     
     
     
          

