name: Creation of Azure_VM
on:
  push:
    branches: dev
jobs:
  review:
    runs-on: self-hosted
    environment: review
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: azure view deployment changes
        run: |
              cd terraform_code
              terraform init
              terraform plan
   
  DEV:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
 
      - name: create azure_vm in DEV ENV
        run: |
              cd terraform_code
              terraform init
              terraform apply
    
  
  QA:
    runs-on: self-hosted
    environment: qa
    needs: DEV
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create azure_vm in QA ENV
        run: |
              cd terraform_code
              terraform apply
      
  PRE-PROD:
    runs-on: self-hosted
    environment: pre-prod
    needs: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
          
      - name: create Azure_vm in Pre-prod ENV
        run: |
              cd terraform_code
              terraform apply
     
     
     
          

